name: venv_econ726  # Name of your environment
channels:
  - conda-forge  # Channel to search for packages
  - defaults  # Default channel
dependencies:
  - python=3.11  # Specify Python version
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - tabulate
  - geopandas
  - shapely
  - folium
  - python-dotenv
  - openpyxl
  - pip
  - pip:
    - sodapy
    - polars
    - statsforecast